apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-nginx
  template:
    metadata:
      labels:
        app: latency-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: latency-nginx-service
spec:
  selector:
    app: latency-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort
